name: Build recommendation service

on:
  push:
    branches:
      - dev/release-test

jobs:

  build:
    uses: ulcheyev/mm-infrastructure/.github/workflows/docker-commons.yml@main
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check reusable workflow outputs
        run: |
          echo "Reusable DOCKERHUB_USER: ${{ needs.build.outputs.dockerUser }}"

#      - name: Build and push Docker image with Jib
#        env:
#          DOCKERHUB_USER: ${{ needs.build.outputs.dockerUser }}
#          DOCKERHUB_PASSWORD: ${{ needs.build.outputs.dockerPassword }}
#        run: |
#          mvn clean verify jib:build \
#            -Djib.to.image=${{ secrets.DOCKERHUB_USER }}/mm-recommendation-service:${{ github.sha }} \
#            -Djib.to.auth.username=${{ secrets.DOCKERHUB_USER }} \
#            -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Trigger re-deploy
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.AGGREGATOR_TOKEN }}
#          repository: ulcheyev/mm-infrastructure
#          event-type: recommendation-service-builded
#          client-payload: '{"service": "mm-recommendation-service", "tag": "${{ github.sha }}"}'
