name: Build recommendation service

on:
  push:
    branches:
      - dev/release-test
      - main
jobs:


  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and push Docker image with Jib
        env:
          DOCKERHUB_USER: ${{ needs.build.outputs.dockerUser }}
          DOCKERHUB_PASSWORD: ${{ needs.build.outputs.dockerPassword }}
        run: |
          mvn clean verify -DskipTests jib:build \
            -Djib.to.image=${{ secrets.DOCKERHUB_USER }}/mm-recommendation-service:latest \
            -Djib.to.auth.username=${{ secrets.DOCKERHUB_USER }} \
            -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Trigger redeploy
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          repository: mankis-movie-mate/mm-infrastructure
#          event-type: recommendation-service-builded
#          client-payload: '{"service": "mm-recommendation-service", "tag": "latest"}'
#          token: ${{ secrets.MM_TOKEN }}
